### ISSUE TITLE
The voice connection is not established in 15 seconds

### ISSUE THREAD

**Issue by CoolMusic1** [Deivu/Shoukaku#143]
Our bot is using this package and in some guild we are getting this error.

The voice connection is not established in 15 seconds

Can we get some idea to fix it ?

We are using version 3.4.0

Regards,

**Comment by flav28** [comment]
Do you check if the bot has the following permissions connect and view channell ?
And which li do you use ?

**Comment by Deivu** [comment]
Usually this happens when your websocket connection to Discord is unstable, or Discord failing to provide you the required data to connect to a voice connection. 

You can either: try again after x amount of time, or fail the connection completely. You can't remove this error, however you can check the error message and if contains this message, then you can do whatever I suggested above.

**Comment by CoolMusic1** [comment]
> Do you check if the bot has the following permissions connect and view channell ? And which li do you use ?

we don't know what permissions bot have in the server but bot sends a message when it dont have necessary permissions like connect viewchannel etc.

We are using node.js
